version: "3"

vars:
  INPUT: ./src/resume.typ
  OUTPUT: ./assets/resume

tasks:
  compile:
    cmds:
      - task: compile:pdf
      - task: compile:png
  compile:*:
    desc: Compile resume in specified format (pdf, png)
    vars:
      FORMAT: "{{index .MATCH 0}}"
    cmds:
      - mkdir -p ./assets
      - export TYPST_FEATURES=html
      - typst compile "{{.INPUT}}" "{{.OUTPUT}}.{{.FORMAT}}" --root . --format {{.FORMAT}}
    silent: true
  preview:
    desc: Preview resume in browser
    cmds:
      - tinymist preview ./src/main.typ --partial-rendering true --root .
    silent: true
