name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile to PDF
        run: make compile

      - run: ls

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: main.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Resume — ${{ env.DATE }}"
          files: main.pdf
          tag: "release-${{ env.DATE }}"
